FROM fedora

# Install any necessary packages
RUN yum update -y && \
    yum install -y yum-utils && \
    # Add Red Hat's Docker repository
    yum-config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo && \
    yum update -y && \
    yum install -y \
    vim nano python3 zip unzip \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

RUN curl "https://corretto.aws/downloads/resources/15.0.2.7.1/amazon-corretto-15.0.2.7.1-linux-x64.tar.gz" -o amazon-corretto-15.0.2.7.1-linux-x64.tar.gz && \
    tar -xvzf amazon-corretto-15.0.2.7.1-linux-x64.tar.gz

RUN ls -la
RUN mkdir -p /usr/src/app && cp -rf amazon-corretto-15.0.2.7.1-linux-x64 /usr/src/app/amazon-coretto-jdk && rm -rf amazon-corretto-15.0.2.7.1-linux-x64

ENV JAVA_HOME=/usr/src/app/amazon-coretto-jdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Add a command that runs continuously
CMD tail -f /dev/null
