FROM registry.access.redhat.com/ubi8/ubi

# Install any necessary packages
RUN cd /etc/yum.repos.d/ && \
    sed -i 's/mirrorlist/#mirrorlist/g' *.repo && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' *.repo

# Register the system (Ensure you have a valid subscription)
# RUN subscription-manager register --username=<YOUR_USERNAME> --password=<YOUR_PASSWORD> (Uncomment and provide your credentials)

# Install necessary packages
RUN yum update -y && \
    yum install -y yum-utils && \
    yum install -y \
    vim nano python3 zip unzip \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin && \
    yum clean all && \
    rm -rf /var/cache/yum

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

# Install Amazon Corretto JDK
RUN curl -o OpenJDK8U-jdk_x64_linux_hotspot_8u362b09.tar.gz https://corretto.aws/downloads/resources/15.0.2.7.1/amazon-corretto-15.0.2.7.1-linux-x64.tar.gz && \
    tar -xvzf OpenJDK8U-jdk_x64_linux_hotspot_8u362b09.tar.gz && \
    mkdir -p /usr/src/app && \
    mv amazon-corretto-15.0.2.7.1-linux-x64 /usr/src/app/amazon-coretto-jdk

# Set JAVA_HOME and PATH environment variables
ENV JAVA_HOME=/usr/src/app/amazon-coretto-jdk
ENV PATH="${JAVA_HOME}/bin:/usr/bin:${PATH}"

# Add a command that runs continuously
CMD tail -f /dev/null
