# syntax=docker/dockerfile:experimental
FROM docker:latest

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get install -y \
        python3 \
        curl \
        unzip && \
    rm -rf /var/lib/apt/lists/*

COPY amazon-corretto-15.0.2.7.1-linux-x64 /usr/src/app/amazon-coretto-jdk

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install --user awscli

# Add AWS CLI to PATH
ENV JAVA_HOME=/usr/src/app/amazon-coretto-jdk
ENV PATH="${JAVA_HOME}/bin:/root/.local/bin:${PATH}"

CMD tail -f /dev/null
