# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker Image Build

on:
  push:
    branches:
      - 'ukreddy*'
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
#env:
#  container_registry: 'qusw-pop-erwin-mart-docker-prod-local.jfrog.io/erwin' #'acrewnmrtshareddevwestus2.azurecr.io' #'martcloud.azurecr.io' #'martserverlinux.azurecr.io'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v2
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(branchname=${GITHUB_REF#refs/heads/};echo ${branchname,,})"
        id: extract_branch
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # extract branch name on pull request
      - name: Extract branch name on Pull Request
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(branchname=${GITHUB_REF};echo ${branchname,,})"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - name: My step
        run: echo ${SHORT_SHA}
      - name: Download Dependencies
        run: |
          curl -o apache-tomcat-8.5.35.tar.gz https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.35/bin/apache-tomcat-8.5.35.tar.gz
          tar -xvzf apache-tomcat-8.5.35.tar.gz
          curl -o OpenJDK8U-jdk_x64_linux_hotspot_8u362b09.tar.gz https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u362-b09/OpenJDK8U-jdk_x64_linux_hotspot_8u362b09.tar.gz
          tar -xvzf OpenJDK8U-jdk_x64_linux_hotspot_8u362b09.tar.gz
      - name: Build and push jenkins image
        run: |
          docker build . -t uday1kiran/tomcatserver-centos:${BRANCH_NAME}-${SHORT_SHA} -f Dockerfile_tomcat_centos
          docker push uday1kiran/tomcatserver-centos:${BRANCH_NAME}-${SHORT_SHA}
